# Generated by Django 4.0.6 on 2022-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
